% MATLAB Editor Run Commands
% @version 4
% It is recommended that you do not edit this file directly, but use the
% Run button. Changes made to comments that exist outside of a
% configuration will not be saved.

%% @name TANK
%  @associatedFile /MATLAB Drive/TANK.m
%  @mostRecentlyActioned true
%  @uniqueId 0FCDDBC5

TANK

%% @name FourTankSystemSensor
%  @associatedFile /MATLAB Drive/FourTankSystemSensor.m
%  @mostRecentlyActioned true
%  @uniqueId 133C972C

FourTankSystemSensor

%% @name FourTankSystem
%  @associatedFile /MATLAB Drive/FourTankSystem.m
%  @mostRecentlyActioned true
%  @uniqueId 300BD1FD

FourTankSystem

%% @name VanDerPol_2
%  @associatedFile /MATLAB Drive/VanDerPol.m
%  @mostRecentlyActioned true
%  @uniqueId 5F309501

VanDerPol(t, x, mu)

%% @name VanDerPol
%  @associatedFile /MATLAB Drive/VanDerPol.m
%  @mostRecentlyActioned false
%  @uniqueId 6D239883

VanDerPol

%% @name FourTankSystemOutput
%  @associatedFile /MATLAB Drive/FourTankSystemOutput.m
%  @mostRecentlyActioned true
%  @uniqueId 683BC5D4

FourTankSystemOutput

%% @name Solution
%  @associatedFile /MATLAB Drive/Solution.m
%  @mostRecentlyActioned true
%  @uniqueId EC97B566

Solution

%% @name SolutionDiscrete
%  @associatedFile /MATLAB Drive/SolutionDiscrete.m
%  @mostRecentlyActioned true
%  @uniqueId A2565D75

SolutionDiscrete

%% @name SolutionLorentz
%  @associatedFile /MATLAB Drive/SolutionLorentz.m
%  @mostRecentlyActioned true
%  @uniqueId 1EA5DB7E

SolutionLorentz

%% @name SolutionRobertson
%  @associatedFile /MATLAB Drive/SolutionRobertson.m
%  @mostRecentlyActioned true
%  @uniqueId 1DB91296

SolutionRobertson

%% @name SolutionBrusselator
%  @associatedFile /MATLAB Drive/SolutionBrusselator.m
%  @mostRecentlyActioned true
%  @uniqueId 3A795D37

SolutionBrusselator

%% @name HovoraSolution
%  @associatedFile /MATLAB Drive/HovoraSolution.m
%  @mostRecentlyActioned true
%  @uniqueId 1F4609A7

HovoraSolution

%% @name ExplicitEulerFixedSS
%  @associatedFile /MATLAB Drive/ExplicitEulerFixedSS.m
%  @mostRecentlyActioned true
%  @uniqueId E51E5CE6

ExplicitEulerFixedSS

%% @name func1
%  @associatedFile /MATLAB Drive/func1.m
%  @mostRecentlyActioned true
%  @uniqueId A65C678C

func1

%% @name Solution2B
%  @associatedFile /MATLAB Drive/Solution2B.m
%  @mostRecentlyActioned true
%  @uniqueId DEEAF226

Solution2B

%% @name VanderPolfunjac
%  @associatedFile /MATLAB Drive/VanderPolfunjac.m
%  @mostRecentlyActioned true
%  @uniqueId 09F56B60

VanderPolfunjac

%% @name Solution4B
%  @associatedFile /MATLAB Drive/Solution4B.m
%  @mostRecentlyActioned true
%  @uniqueId A9B15E40

Solution4B

%% @name Solution3
%  @associatedFile /MATLAB Drive/Solution3.m
%  @mostRecentlyActioned true
%  @uniqueId 0C5E172B

Solution3

%% @name ExplicitEulerAdaptiveStep
%  @associatedFile /MATLAB Drive/ExplicitEulerAdaptiveStep.m
%  @mostRecentlyActioned true
%  @uniqueId 7B0CF84E

ExplicitEulerAdaptiveStep

%% @name PlugFlowReactor_firstorder
%  @associatedFile /MATLAB Drive/PlugFlowReactor_firstorder.m
%  @mostRecentlyActioned true
%  @uniqueId 8BA257A7

PlugFlowReactor_firstorder

%% @name Solution6B
%  @associatedFile /MATLAB Drive/Solution6B.m
%  @mostRecentlyActioned true
%  @uniqueId 653318CF

Solution6B

%% @name Solution6B2
%  @associatedFile /MATLAB Drive/Solution6B2.m
%  @mostRecentlyActioned true
%  @uniqueId 529CB655

Solution6B2

%% @name ClassicRK4Solution
%  @associatedFile /MATLAB Drive/ClassicRK4Solution.m
%  @mostRecentlyActioned true
%  @uniqueId 7493A664

ClassicRK4Solution

%% @name ClassicalRungeKuttaStep
%  @associatedFile /MATLAB Drive/ClassicalRungeKuttaStep.m
%  @mostRecentlyActioned true
%  @uniqueId 785EF513

ClassicalRungeKuttaStep

%% @name teststability
%  @associatedFile /MATLAB Drive/teststability.m
%  @mostRecentlyActioned true
%  @uniqueId DD9009AF

teststability

%% @name ClassicRK4Solution2
%  @associatedFile /MATLAB Drive/ClassicRK4Solution2.m
%  @mostRecentlyActioned true
%  @uniqueId D72FF80C

ClassicRK4Solution2

%% @name ERKSolverErrorEstimation
%  @associatedFile /MATLAB Drive/ERKSolverErrorEstimation.m
%  @mostRecentlyActioned true
%  @uniqueId CDB55D31

ERKSolverErrorEstimation

%% @name Exam1
%  @associatedFile /MATLAB Drive/Exam1.m
%  @mostRecentlyActioned true
%  @uniqueId 809E438B

Exam1

%% @name ImplicitEulerAdaptiveStep
%  @associatedFile /MATLAB Drive/ImplicitEulerAdaptiveStep.m
%  @mostRecentlyActioned true
%  @uniqueId 01B9719E

ImplicitEulerAdaptiveStep

%% @name Exam2info
%  @associatedFile /MATLAB Drive/Exam2info.m
%  @mostRecentlyActioned true
%  @uniqueId C0A2648A

Exam2info

%% @name CSTR1d
%  @associatedFile /MATLAB Drive/CSTR1d.m
%  @mostRecentlyActioned true
%  @uniqueId 18B4422A

CSTR1d

%% @name Solution_CSTR
%  @associatedFile /MATLAB Drive/Solution_CSTR.m
%  @mostRecentlyActioned true
%  @uniqueId B244DF6E

Solution_CSTR

%% @name ExamCompareMethod
%  @associatedFile /MATLAB Drive/ExamCompareMethod.m
%  @mostRecentlyActioned true
%  @uniqueId B854E1CB

ExamCompareMethod

%% @name ExamCompareMethod2
%  @associatedFile /MATLAB Drive/ExamCompareMethod2.m
%  @mostRecentlyActioned true
%  @uniqueId 6B5911E2

ExamCompareMethod2

%% @name ExamStiffVDP
%  @associatedFile /MATLAB Drive/ExamStiffVDP.m
%  @mostRecentlyActioned true
%  @uniqueId AC7BCC00

ExamStiffVDP

%% @name SolutionCSTR3d
%  @associatedFile /MATLAB Drive/SolutionCSTR3d.m
%  @mostRecentlyActioned true
%  @uniqueId 98A4AEC2

SolutionCSTR3d

%% @name CSTR3d
%  @associatedFile /MATLAB Drive/CSTR3d.m
%  @mostRecentlyActioned true
%  @uniqueId 4A3AD107

CSTR3d

%% @name CSTR_ExpEuler
%  @associatedFile /MATLAB Drive/CSTR_ExpEuler.m
%  @mostRecentlyActioned true
%  @uniqueId 0144E897

CSTR_ExpEuler

